### ISSUE TITLE
I cannot use this library in my project because for the license

### ISSUE THREAD

**Issue by spielcrypto** [asonix/tokio-zmq#13]
I would like to do a broker mesage framework using this library but my project would be MIT License because my intetion is that the developer can use it in their private sources if they want, but with the license of this library I cannot include it. Is your intention turn this is dual license?

**Comment by asonix** [comment]
No, my intention is to leave this under the GPL version 3

**Comment by spielcrypto** [comment]
Could I fork the repository rename it, create new version and changue the license to MIT and maintence for myself? Are you agree?

**Comment by asonix** [comment]
No, that would be considered a derivative work and the terms of the GPLv3 would still apply. I am not willing to grant alternative license terms for this project
